### ISSUE TITLE
[blog] PHASE 1 COMPLETED cannot see image

### ISSUE THREAD

**Issue by PAOLOALF** [lagobello/lagobello-www-hugo-universal#2]
There is an image in file that is not visible in https://www.lagobello.com/blog/2018/04/27/phase-1-completed/

**Comment by vittorio88** [comment]
Failed to load resource: the server responded with a status of 404 ()

**Comment by vittorio88** [comment]
Fixed in e6a9ae4645a5d4ed648d365f1f907dd98a1c9de6
