### ISSUE TITLE
[map] MEDIDAS

### ISSUE THREAD

**Issue by PAOLOALF** [lagobello/lagobello-www-hugo-universal#3]
HAY QUE METER UNA HOJA DE EXEL CON MEDIDAS COMO ESTAN EN LOS DISEGNOS DE INGENIERIA

**Comment by vittorio88** [comment]
Possibly use https://github.com/Turfjs/turf/tree/master/packages/turf-intersect to calculate lot length.

**Comment by vittorio88** [comment]
Fixed in 06559c01cd758bff42afc33cce1da1d205322898.
